import streamlit as st
import pandas as pd
import numpy as np
import altair as alt
import matplotlib.pyplot as plt

st.set_page_config(layout="wide")
st.title('💰Cryptocurrency Pool Data Viewer💰')

#import the dataframe generated by main structure
# data = pd.read_csv('/Users/edithliu/Desktop/AP/data.csv')
# st.line_chart(data=data, x = None, y = "umami_TVL")

get_data = pd.read_csv('/Users/edithliu/Desktop/AP/display/display_dataframe.csv')

protocols_dict = {}
counter = 0
column_list = get_data['protocol'].tolist()
for protocols in column_list:
    protocols_dict[protocols] = counter
    counter = counter + 1

protocols_list = ["gmx", "frax-finance", "convex-finance", "curve-finance", "synthetix", 'dYdX', 'gains-network', 'umami-finance', 'LooksRare', 'Beefy', 'ribbon', 'redacted-protocol', 'dopex', 'kujira-protocol', 'polynomial-protocol','Lido', 'MakerDAO', 'aave', 'JustLend', 'uniswap', 'compound-finance', 'pancakeswap', 'venus', 'pendle', 'morpho']
protocols_list = [element.lower() for element in protocols_list]
protocols = st.multiselect("Choose protocols", protocols_list)
st.subheader('⏰Lastest 24h data')
if not protocols:
    st.error("Please select at least one portocol.")
else:
    up_col1, up_col2 = st.columns(2)
    with up_col1:
        indexes = []
        for k in protocols:
            print(k)
            indexes.append(protocols_dict[k])
        data = get_data.iloc[indexes]
        # st.write(data)
        data = data.drop(columns='Unnamed: 0')
        st.data_editor(
        data,
        column_config={
            "logos_urls": st.column_config.ImageColumn(
                "Logo", help="Streamlit app preview screenshots"
            )
        },
        hide_index=True,
        )

        risk_count = pd.DataFrame(data.value_counts("Risk Level"))
        st.bar_chart(data = risk_count, color="#653e87")

    with up_col2:
        st.subheader('Total Volume')
        st.bar_chart(data = data,x = "protocol", y ="volume",color = "#DE3163")

        st.subheader('TVL')
        st.bar_chart(data = data,x = "protocol", y ="TVL")
        
    # with col2:
    #     st.subheader('APY')
    #     st.bar_chart(data = data,x = "protocol", y ="APY", color="#088F8F")

   


